### ISSUE TITLE
What puzzles you most about Angular?

### ISSUE THREAD

**Issue by juristr** [juristr/ama#12]
Hey, I'd like to know

- where you're struggling with Angular
- what you find most difficult when getting started with Angular or when developing with it
- what would you like to see me post/talk/create [Egghead lessons](https://egghead.io/instructors/juri-strumpflohner) for
- ...

The scope of this is to understand better the struggles you're having and accordingly try to provide some better learning material for those areas 😃

**Comment by mohammedzamakhan** [comment]
Hi @juristr 

I want few features in Angular which you might find in other lib/frameworks ex: React (with TypeScript):
- Validations of Inputs using language services,  like we should be able to get error in our template if we do not use a required input or if we do not pass a correct type to the input 
- Simpler way to lazy load components, in React you only import and use React.lazy, rather than the need to create a module and add it lazyModules in angular.json and then loading it lazily

**Comment by juristr** [comment]
@mohammedzamakhan Good input man. You should also give this feedback back to the Angular team using this survey: https://t.co/a30NPJn9Sw?amp=1

I agree with the lazy loading of components, this should get a bit easier post-Ivy I guess.

Could you go more into details on this one? 

> Validations of Inputs using language services,  like we should be able to get error in our template if we do not use a required input or if we do not pass a correct type to the input

What exactly do you mean here with "Validations of Inputs using language services"?

**Comment by mohammedzamakhan** [comment]
> What exactly do you mean here with "Validations of Inputs using language services"?


https://github.com/angular/angular/issues/25545#issuecomment-458718392
