### ISSUE TITLE
Workout Routine

### ISSUE THREAD

**Issue by smedavarapu** [juristr/ama#14]
I guess AMA does not have to be technical always. Here is what I am curious to know about. Your body looks lean and athletic.
1) What is your Workout Routine
2) What is your Meal plan?
3) Planning to write any article on this topic?

**Comment by juristr** [comment]
Hey, no it doesn't necessarily have to be technical 😄 .

Well...I think I'll have to disappoint you a bit 😅 , as I don't really follow a strict meal plan. Been struggling a bit with my workout routine lately (didn't work out for 1 1/2 weeks due to workshop & public speaking prep and other work related stuff). But now I'm back again.

I'm doing martial arts (Yoseikan Budo) already for 18 years (high school onwards) and that's what my usual workout routine looks like:

- Monday class: 1 hour cardio training, followed by 2 hours martial arts training
- Wednesday class: 1 hour cardio training
- Friday (occasionally): 2 hours martial arts training

That's my average plan I'll try to follow throughout the year, although as mentioned I'm struggling to follow it exactly like that from now and then, but that's ok.

Martial arts training is quite intense and a full-body workout. What I plan to do again - most probably after the holidays - is to pick up again with my calisthenics workouts. I've done those from July 2016 to like July 2017 on a very regular basis, which is like in summer (when there's no martial arts training), I exercised on Monday, Wednesday, Friday and Sunday. That gave me a huge gain in muscles & strengths. Then once martial arts classes started again in October, I switched to exercise calisthenics on Tuesday, Wednesday and Sunday.

That's what I plan to do again, but most probably just 2 days of calisthenics, as I won't be able to do it for work reasons. I got the calisthenic exercises from [Calimove](https://plan.eleggs.de/). They have a lot of [awesome Youtube Videos](https://www.youtube.com/channel/UCZIIRX8rkNjVpP-oLMHpeDw) as well & an Instagram account. I asked them to create a specific training plan for me and followed that one.

For meal plan...well that's my biggest hurdle, but at the same time the most important one. I'm lucky to have good genetic predisposition.. 😅
