### ISSUE TITLE
Question about your talk on packaging angular module

### ISSUE THREAD

**Issue by bhaidar** [juristr/ama#15]
Hi Juri,

I am following your video here: https://www.youtube.com/watch?v=K4YMmwxGKjY

When I try to run yarn run build:inline, I get the following:

`yarn run build:inline
yarn run v1.5.1

$ rsync -a *.ts ./tmp && node inlineAssets.js

'rsync' is not recognized as an internal or external command,
operable program or batch file.
error An unexpected error occurred: "Command failed.
Exit code: 1`

Any idea how to make this work? 

Thanks
Bilal

**Comment by juristr** [comment]
Hey, are you on Windows? Because if you are then that's probably the issue. `rsync` is a unix only command, my bad, sorry.

But if you're building libraries, I'd now highly suggest to use `ng-packagr`. you can check out the various branches I have [on the repo](https://github.com/juristr/ngx-tabs-libdemo) and also my [talk from ngVikings](https://www.youtube.com/watch?v=Tw8TCgeqotg).

Hope that helps, otherwise let me know by re-opening the issue. I also plan to release a blog post about this in the coming weeks...just need to find some time :)

**Comment by bhaidar** [comment]
Thanks Juri for the reply! Yes I am on Windows. I had to replace it with
copyfiles and it works fine now. It is such a very useful session to go
into the details on how things work manually. Front-end development is
really getting more complicated!

I've got to ask myself the question for the difference between webpack and
rollup. I see both create a module file that browser understands. I believe
I understood that both translate the CommonJS (require) into something
browser understands.

Thanks again
Bilal

On Wed, May 2, 2018 at 4:47 PM, Juri Strumpflohner <notifications@github.com

**Comment by juristr** [comment]
yes indeed, the session's goal was to show what's going on behind the scenes 😊

Webpack and Rollup are very similar. Webpack is more optimized for compiling and bundling web applications, like your Angular or React app etc. It does a bunch of stuff actually 🙂
Rollup on the other side is better suited for building libraries in my opinion. And it is better for tree shaking, at least until recenlty. Latest versions of webpack got quite good actually.

**Comment by bhaidar** [comment]
Thanks again @juristr 
I was wondering that Webpack would prepare and package module. It is Angular that decides that now I need to download this module from the server? Especially in the case of lazy loading modules? Or is it Webpack that does that?

**Comment by juristr** [comment]
> I was wondering that Webpack would prepare and package module. It is Angular that decides that now I need to download this module from the server?

Webpack happens at **compile time** while Angular (if you want) at **runt-time**. So they're actually both somehow involved. When you use lazy modules (i.e. via Angular's routing), then the Angular CLI analyzes your code and detects lazy loading instructions. Underneath the CLI uses Webpack (right now), and instructs it therefore to create a dedicated JavaScript bundle file containing the lazy loaded content.

Then **at runtime**, when the lazy loaded route is hit, Angular actually calls the proper instruction to load the script over the network and bootstrap it.

At runtime, i.e. when you deploy your app, Webpack should be gone. That's just a tool you use for development. Many people confuse this, because when they run their app in development, they use Webpack (more specifically the internal webpack dev server) to serve the app. In Angular you usually do so by invoking the `ng serve` command, which boots up the Webpack dev server. This however, is just a development facility, as it makes it easy to see the changes and refresh them incrementally in your browser, without the need to every time compile and compress the entire application which would be time consuming.

Hope I could clarify your doubts. have a nice day 😄
