### ISSUE TITLE
Data flow between M-V-C

### ISSUE THREAD

**Issue by Colum** [juristr/ama#5]
The propagation of data goes through the controller. I have no issues with seeing how the flow occurs when the user submits a change in the view:
PersonView -> PersonController -> Person

However, when this change occurs, the "Person" class must _firePropertyChange()_ for the changes to 'travel back' to the "PersonView" to be displayed. The method which does this in the "Person" class is _firePropertyChange(..)_ which is inherited from "AbstractModel". This method executes the line :

propertyChangeSupport.firePropertyChange(propertyName, oldVal, newVal);

where _propertyChangeSupport_ is type PropertyChangeSupport and is an instance var in the "AbstractModel" class.

My question is, how does this line propagate the data back to the controller? I dont see the link between this variable and the "PersonController".

Thank you!

**Comment by juristr** [comment]
Hi @Colum,

wow, you dug out quite an old post, back from the early days of my 1st programming experiments 😃. I wouldn't take this too serious 😉, but still the example is a valid experiment of mine to implement an MVC pattern.

First of all, you can [download the demo jar file here](http://juri-strumpflohner-projects.googlecode.com/files/mvcdemo1.0.jar), surprisingly it's still available although Google Code closed down in the meanwhile. If you open the jar with a zip utility, you also get the src files.

> My question is, how does this line propagate the data back to the controller? I dont see the link between this variable and the "PersonController".

So in the `ApplicationController.java` all components are linked together:

``` java
...
Person p = (Person)selectedValue;
pController = new PersonController();
PersonView pView = new PersonView(pController);
pController.addModel(p);
pController.addView(pView);
...
```

Now, if the `Person` class fires the change listener, as you correctly state, in the `AbstractModel` the according `propertyChangeSupport.firePropertyChange(propertyName, oldVal, newVal);` is invoked. The `PersonController` inherits from `AbstractController`, which contains the method `addModel(..)` which we've just seen:

``` java
public void addModel(AbstractModel model) {
    ...
    model.addPropertyChangeListener(this);
}
```

Look at this line. Here, the controller instance - in our case the `PersonController` registers itself as a change listener on the `AbstractModel`, here `Person`. Note that the controller passes "himself" -> `this` to the `addPropertyChangeListener`. This is because `AbstractController` implements `PropertyChangeListener` and thus also defines the according `propertyChange` method. That function gets invoked, when the `AbstractModel` invokes `propertyChangeSupport.firePropertyChange(propertyName, oldVal, newVal);`. Let's take a look at it's implementation:

``` java
public void propertyChange(PropertyChangeEvent evt) {
    for (IView view: registeredViews) {
        view.modelPropertyChange(evt);
    }
}
```

As you can see, what it does is to iterate over the registered views (remember we registered the view to the controller before -> `pController.addView(pView);`) and calls the according `modelPropertyChange(...)` method, passing on the parameter.

So this is how the data flows from the `Person` (Model) => `AbstractModel` => registered PersonController (Controller) => PersonView (View).

Note that meanwhile other data flow patterns have emerged over the years, depending in which environment you're working (web, desktop, mobile,..)

Hope that was useful 😄

**Comment by Colum** [comment]
That was pretty helpful! To confirm, when the `AbstractModel` invokes `propertyChangeSupport.firePropertyChange(name, new, old)` it automatically tells its subscribers to execute their `propertyChange(..)` method? im debugging line by line and it seems as though the execution jumps from one to the other without mention of the method name.
