### ISSUE TITLE
Property 'target' and also length does not exist on type '{}' - angular 2

### ISSUE THREAD

**Issue by WaqarMH** [juristr/ama#6]
``` javascript
import { Component } from '@angular/core';
import { Http } from '@angular/http';
import { Observable } from 'rxjs/observable';
import 'rxjs/Rx';

@Component({
moduleId: module.id,
selector: 'app-root',
template: '<input type="text" id="search" placeholder="Write Something" class="input input-lg">',
styleUrls: ['app.component.css'],
})

export class AppComponent {
        constructor() {
            var keyups = Observable.fromEvent(document, 'keyup')
            .map(e => e.target.value)  //[ts] Property 'target' does not exist on type '{}'.any
            .debounceTime(200)
            .filter(text => text.length >= 3); //Property 'length' does not exist on type '{}'.

            keyups.subscribe(data => console.log(data));
        }
}
```

![screenshot_94](https://cloud.githubusercontent.com/assets/13906186/18608151/d1807bb4-7cfa-11e6-949f-4d9f9d1cb1e7.png)

**Comment by juristr** [comment]
Hi @WaqarMH,

I'm not sure what your end goal of this component is. Based on the comments you added, I assume this is just a TypeScript error. To fix it, you can add the according type annotations.

``` typescript
...
import { KeyboardEvent} from '@angular/core';

@Component({..})
export class AppComponent{

   constructor() {
      Observable.fromEvent(document, 'keyup')
         .map((e:KeyboardEvent) => e.target.value)
         .debounceTime(200)
         ...
  }
}
```

I didn't try it out myself, but I think this should work. **Hint:** in order to get to know which type you get within a certain function, you can simply log it out to the console:

``` javascript
Observable.fromEvent(document, 'keyup')
   .map(e => {
      console.log(e);
      return e.target.value;
   });
```

which gets you the following:

![image](https://cloud.githubusercontent.com/assets/542458/18608627/02726ac2-7cef-11e6-912f-e918858c07e0.png)

## Register events on `document`

Regarding your actual intentions, I would avoid accessing global variables which live outside your component like `document` as much as possible. This is somehow considered bad practice. In order to hook up an event listener on `document` you can use the `host` property or `@HostListener` annotations:

``` typescript
@Component({
   ...
   host: {
      '(document:keyup)': 'onDocumentKeyUp($event)'
   }
})
export class AppComponent {
   ...

   onDocumentKeyUp(ev: KeyboardEvent) {
      console.log(ev.key);
   }
}
```

Alternatively the `@HostListener` decorator, which I personally prefer:

``` typescript
@Component({...})
export class AppComponent {

   @HostListener('document:keyup', ['$event'])
   onDocumentKeyUp(ev:KeyboardEvent) {
      console.log(ev.key);
   }
}
```

Here's a Plunker to play around with this: https://plnkr.co/edit/ZgbCJhAxk2P95yNxDWvC?p=preview

## Registering an event on the textbox

You could also simply register the keyup listener on your input box itself, always using the `(..)` syntax in your template:

``` html
<input type="text" (keyup)="onKeyUp($event)">
```

Example: https://plnkr.co/edit/cgfCsPPEQkgxwg3XSiIN?p=preview

Really hope this was helpful 😄

**Comment by juristr** [comment]
@WaqarMH "one more thing" 😉 

You can also make use of Angular 2's `ReactiveForms` like this:

``` typescript
@Component({
  selector: 'my-app',
  template: `
    <div>
      <h2>Hello {{name}}</h2>
      <input type="text" [formControl]="searchInput">
      <hr />
      <ul>
        <li *ngFor="let val of typedValues">
          {{ val }}
        </li>
      </ul>
    </div>
  `
})
export class App {
  searchInput = new FormControl();
  typedValues = [];

  constructor() {
    this.name = 'Angular2'

    this.searchInput.valueChanges
      .debounceTime(200)
      .subscribe(val => {
        this.typedValues.push(val);
      });
  }
}
```

Here is the full Plunker with all the required imports: https://plnkr.co/edit/pNTXBoriqTj9j9Hsrsjb?p=preview

If you're new to Forms in Angular 2 you may want to check out my article which gives you a first overview and starting point: http://juristr.com/blog/2016/08/ng2-forms-first-look/

enjoy 😄
